### ISSUE TITLE
0.4.2 CHANGELOG says "drop-in replacement" but the published POM dropped 4 runtime deps (slf4j, logback, clikt, kotlin-reflect)

### ISSUE THREAD

**Issue by monkopedia-coder** [Monkopedia/hauler#30]
## Code-health suggestion (proactive — staged for your review)
**Category:** hygiene (inaccurate release note on a shipped artifact)

**Where:** `CHANGELOG.md:42-43`, and the published `hauler-jvm` POM on Maven Central.

**Current:** the 0.4.2 entry closes with

> _No public API/ABI changes in this release; `hauler` 0.4.2 is a drop-in replacement for 0.4.1 for consumers._

**The published POM says otherwise.** Diffing the two artifacts as they actually exist on Central (both HTTP 200):

```
hauler-jvm-0.4.1.pom (4136 bytes)   ->   hauler-jvm-0.4.2.pom (3274 bytes)

REMOVED:
  org.jetbrains.kotlin:kotlin-reflect           (compile AND runtime entries)
  org.slf4j:slf4j-api:2.0.17                    runtime
  com.github.ajalt.clikt:clikt-jvm:5.1.0        runtime
  ch.qos.logback:logback-classic:1.5.32         runtime
```

These came out with #6 ("Remove unused JVM dependencies"), which the CHANGELOG files under **"Internal (no public API change)."** They were unused *by hauler* — that part is right, and removing them was the correct change. But `implementation(...)` in `jvmMain` publishes as `runtime` scope, so they were on every consumer's runtime classpath, and now they are not.

**Concretely, for a consumer upgrading 0.4.1 → 0.4.2 who was resolving these transitively:** `kotlin-reflect`, `slf4j-api` and `clikt` disappear from the runtime classpath (`NoClassDefFoundError` on first use), and `logback-classic` disappearing means SLF4J has no binding — the familiar *"SLF4J: No providers were found"* plus silently discarded logging, which for a logging library is a particularly bad way to find out.

**Note this is not an argument to put them back.** A library exporting a logging *backend* transitively is bad practice and #6 fixed a real problem. The defect is the release note: a change with consumer-visible runtime consequences is recorded as having none, so nobody upgrading reads a warning that would take one line.

**Why the release verification did not catch it — the part worth keeping.** I checked 0.4.2 with `apiCheck` and reported "zero apiDump drift, konstructor-safe." That was true and it was not evidence for the claim I attached to it: **BCV does not look at the POM at all.** The dependency graph is not part of the API dump, so a check that is working perfectly cannot see this class of change. Combined with what is already filed, that is three distinct things the 0.4.2 gate did not cover:

1. the native/JS/Wasm ABI — `klibApiCheck` is a disabled no-op (#21);
2. test execution on 7 of 11 platform targets (#22);
3. **the published dependency graph — no instrument, on any platform, at any time.**

Only the third is new here, and it is the only one where a consumer-visible change actually shipped.

**Proposed:**
1. Correct the 0.4.2 entry — move the #6 bullet out of "Internal (no public API change)" and add a short **Removed (may affect consumers)** note naming the four coordinates and telling anyone who relied on the transitives to declare them directly.
2. Consider whether a release checklist should diff the published POM against the previous release. It is two `curl`s and it is the only thing that would have caught this.

**Effort:** mechanical for (1); (2) is a decision.

_Filed by the nightly code-health pass. To act on it: relabel `agent-workable` (it'll flow into triage→work). To decline: close it — it won't be suggested again._

**Comment by monkopedia-coder** [comment]
**Reclassifying `needs-decision` → `agent-workable`, SCOPED, under `triage-subagent.md:134-137` and the scoped-dispatch pattern at `:141`. Reasoning recorded so a reviewer can check it.**

**This issue contains two things and only one of them needs you.** Splitting them by comment rather than by filing a second issue, to avoid adding to your queue.

**IN SCOPE for an agent, flipping now — proposal 1, the CHANGELOG correction.** The 0.4.2 entry says *"No public API/ABI changes in this release; hauler 0.4.2 is a drop-in replacement for 0.4.1"* while the published POM dropped four runtime dependencies. That is a **false statement in shipped documentation**, and "do you want the release note to be accurate?" is not a question you need to answer. It is the same class as #19, #24, #31 and #32, which I flipped on the same test an hour ago, and I was inconsistent to leave this one behind. Outside hauler's owner-gate read narrowly: 0.4.2 has already shipped, so correcting how it is *described* changes nothing about what ships or how it is versioned. Goes through the PR pipeline.

**STAYS WITH YOU — proposal 2, the release checklist.** *Should the release procedure diff the published POM against the previous release?* That is a real one-sentence question, it changes a process you own, and I am not answering it for you. My recommendation is yes and it costs two `curl`s, but the call is yours.

**An agent picking this up should implement proposal 1 only** and leave proposal 2 untouched.

Also per `triage-subagent.md:126`: self-filed with a confident recommendation attached, which that section names as the biggest single source of false `needs-decision`.

**Comment by monkopedia-coder** [comment]
**Reverting this to `needs-decision` — the label has decayed, and I am the one who decayed it.**

I flipped #30 to `agent-workable` **scoped to proposal 1** (correct the 0.4.2 release notes). That shipped in `e3bb52b`. What remains under the label is **proposal 2 only**:

> *Should the release procedure diff the published POM against the previous release?*

That is a real one-sentence owner question about a process you own, it fails the first condition of `triage-subagent.md:134-137`, and I said so explicitly when I flipped it. So the label now advertises work an agent should not do.

This is the decay case `triage-subagent.md:143` names — *"`agent-workable` can be CORRECT when applied and become WRONG when the work under it finishes"* — and the rule that whoever changes the state owns the label. I merged the PR, so it is mine to put back.

**My recommendation, for whenever you get to it:** yes, and it is two `curl`s. Diffing `hauler-jvm-<prev>.pom` against `hauler-jvm-<new>.pom` at release time is the only check that would have caught the four dropped runtime dependencies — BCV does not read the POM, so `apiCheck` is structurally blind to that whole class regardless of how well it is working. The counter-argument is that it is one more manual step in a release process that is already several, and the failure it catches is rare and non-fatal.

**Comment by monkopedia-coder** [comment]
## Decision from Jason — 2026-08-26: proposal 2 is DECLINED

Presented at the decision desk as: *should the release procedure diff the published POM against the previous release?* (Proposal 1, the 0.4.2 CHANGELOG correction, shipped in `e3bb52b` and was not part of what he was asked.)

**His answer, verbatim, across two messages:**

> this feels like a silly thing to be worried about, our dependencies changed and we're worried about the publication of it? really?

and, when asked whether to close the issue or drop the label:

> even if this fires, we're not going to go re-add stale dependencies just to keep our dependencies the same, so the problem was just the claim of "drop-in replacement"

### What this settles

- **No POM-diff check in the release path.** Not gating, not print-only, not as a manual step.
- **His stated reason, which is the part to keep:** the check would fire on intentional dependency removals, and the response to it would never be to re-add a stale dependency. A detector whose signal you would not act on is not worth building.
- **The defect was the release note, and the release note is fixed.** *"the problem was just the claim of 'drop-in replacement'"* — that claim was corrected in `e3bb52b`. Nothing further is owed here.

### ⚠️ Disposition not stated by him

I asked directly whether to close #30 or leave it open with the label dropped, and **he answered the substance without answering that.** So: he declined the proposal; he did not issue a close instruction. The health-suggestion template on this issue says *"To decline: close it — it won't be suggested again"* — closing is therefore this repo's own documented handling of a decline, **not an instruction from him.** Whoever closes it should say so on that basis and not attribute the close to him.

### ⚠️ A broader statement, recorded as broad — and flagged

*"even if this fires, we're not going to go re-add stale dependencies just to keep our dependencies the same"* generalises into a test for proposed checks: **if you would not act on the signal, do not build the detector.** It is recorded broadly because that is what it says. **But it was said in answer to one narrow question about one check in one repo.** It is not authority to decline other proposed instruments elsewhere. If it looks like it settles such a question, bring that question to the desk and cite this — do not apply the extension yourself.

### Not covered

- **Nothing about kcsg#57's consumer-resolution smoke test.** That is a different instrument (it resolves each published coordinate standalone and compiles against it) in a different repo, answering a different defect, and Jason ruled on 2026-08-26 that kcsg cuts `0.5.1` on the strength of it. **This decline does not touch it.**
- Whether hauler should have any published-artifact check of any other kind. Not asked, not answered.

_Recorded by the decision desk. Posting as `monkopedia-coder` — an agent recording what the owner said, not the owner speaking._

**Comment by monkopedia-coder** [comment]
**Disposition resolved — 2026-08-26.** The prior comment flagged that Jason had declined the proposal without saying whether to close. Asked again, he answered:

> ok, close that last one

Closing on his instruction. This supersedes the "closing is the template's convention, not his instruction" caveat above — it is now his instruction.

**Comment by monkopedia-coder** [comment]
> ## ⚠️ CORRECTION — the premise of this comment was already false when it posted
>
> **It opened by saying the close was on the template's convention "not on an instruction from Jason." That is wrong.** He was asked again and answered *"ok, close that last one"* — recorded in the comment directly above, posted **14 seconds** before this one. The issue was already closed on his instruction while I was writing.
>
> **I read #30 as OPEN + `needs-decision`, reasoned carefully from that state, and published a conclusion whose premise had expired in the interval.** Nothing collided and no file was overwritten — two agents simply worked the same issue at once, and the loser was the one who had read first. Leaving the original text below rather than editing it away, since the failure is the point.
>
> **The close is on Jason's instruction.** My only non-duplicated action here was dropping `needs-decision`, which the close did not remove.

---

## ~~Closing — both proposals are resolved. Closing on this repo's own template, not on an instruction from Jason.~~

~~The decision comment above is explicit that he declined the proposal without saying what to do with the issue, and asks that nobody attribute the close to him. So, stating the basis: the health-suggestion template on this issue reads *"To decline: close it — it won't be suggested again."*~~ **Superseded — see the correction above. The verification below stands; it was about the artifact, not about who closed the issue.**

## Proposal 1 — verified shipped, by reading the artifact rather than the commit message

I did not take `e3bb52b` on relay. Checked against `origin/main` as it stands today:

```
e3bb52b                      IS an ancestor of origin/main
"No public API/ABI changes"  0 occurrences   (the original sentence is gone)
"drop-in"                    1 occurrence out of 73 lines inspected
```

**That surviving occurrence is the fix, not a residue** — it now reads *"Two caveats keep this short of a drop-in replacement,"* followed by both caveats named: the four dropped runtime coordinates, and the unverified native/JS/Wasm ABI across 2.4.0 → 2.4.10. There is a `### Removed (may affect consumers)` section naming all four, and it calls out `logback-classic` as the one most likely to bite.

I checked the **claim's own words**, not just that a new section had appeared, because a correction that adds a caveat while leaving the original sentence standing is a failure mode this repo hit twice this week — a withdrawal filed against one artifact does not propagate to another that repeats the claim.

## Proposal 2 — declined, nothing owed

No POM-diff in the release path, in any form. Recorded above with his reasoning.

## The part of his answer worth keeping, and its limit

> *"even if this fires, we're not going to go re-add stale dependencies just to keep our dependencies the same"*

**If you would not act on the signal, do not build the detector.** That is the *prior* question to the one this repo has been asking all week. The standing rule here is *"a green run is never evidence a gate works — only a deliberate red is"*; his is the question that comes before it: **what would you do if it went red?** For a POM diff on an intentional dependency removal the honest answer is "nothing," and a detector nobody would act on is inert by construction — the same shape as a check that cannot fail, reached from the other end.

**Its limit, per the decision comment and worth repeating where someone will find it:** that was said about one check in one repo, and it is not authority to decline instruments elsewhere. Noting specifically that **#37 passes the test** — a red leg there means a platform suite is genuinely broken, and the response is to fix it — so this decline does not reach it.

Nothing further here. `needs-decision` dropped, since the decision exists.
